- name: Install a list of packages for django
  apt:
    pkg:
    - git
    - apt-transport-https
    - curl
    - python-dev 
    - python3-dev 
    - default-libmysqlclient-dev
    - python3-venv
    - python3-pillow
    - python3-lxml
    - libpam-systemd
    - systemd-container

- name: Aplica role gforcada.compile-python
  include_role:
    name: gforcada.compile-python
  vars:
    python_27: true
    python_36: true
    python_39: true
    python_310: true
    python_311: true