# csv dos swicthes

- name: install freeradius
  apt:
    state: latest
    update_cache: yes
    pkg:
      - freeradius
      - freeradius-mysql
      - freeradius-utils
      - default-libmysqlclient-dev
      - mariadb-client

- include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - pymysql

- name: read from file
  set_fact:
    switchesfile: "{{ lookup('file', '../../files/switches.csv') }}"

- name: csv to list
  set_fact:
   switches: "{{ switchesfile.split('\n') }}"

- name: Initialize  freeradius_clients
  set_fact:
    freeradius_clients: []

- name: monta lista de switches
  set_fact:
    freeradius_clients: >
      {{ freeradius_clients + [{
        'name': item.split(',')[0],
        'ipaddr': item.split(',')[1]
      }]}}
  with_items:
    - "{{ switches }}"

- name: enable freeradius
  service:
    name: freeradius
    enabled: yes

- name: check if table radcheck exists
  shell: >
    mysql
    --host={{ tasks_freeradius_mysql.host }}
    --database={{ tasks_freeradius_mysql.database }}
    --user={{ tasks_freeradius_mysql.user }}
    --password={{ tasks_freeradius_mysql.password }}
    -e 'SHOW TABLES;' | grep -c radcheck
  register: dbstatus
  failed_when: dbstatus.rc == 2

- name: Sobe schema do mysql
  mysql_db:
    name: "{{ tasks_freeradius_mysql.database }}"
    login_host: "{{ tasks_freeradius_mysql.host }}"
    login_user: "{{ tasks_freeradius_mysql.user }}"
    login_password: "{{ tasks_freeradius_mysql.password }}"
    state: import
    target: "/etc/freeradius/{{ freeradius_version }}/mods-config/sql/main/mysql/schema.sql"
  when: dbstatus.stdout == "0"

- name: clients.j2
  template:
    src: "clients_freeradius.j2"
    dest: "/etc/freeradius/{{ tasks_freeradius_version }}/clients.conf"

- name: radius.sql.j2
  template:
    src: "radiusd.conf.j2"
    dest: "/etc/freeradius/{{ tasks_freeradius_version }}/radiusd.conf"
    unsafe_writes: yes
    owner: freerad
    group: freerad

- name: radius sql
  template:
    src: "freeradius.sql.j2"
    dest: "/etc/freeradius/{{ tasks_freeradius_version }}/mods-available/sql"
    owner: freerad
    group: freerad

- name: restart freeradius
  service:
    name: freeradius
    state: restarted
