# https://askubuntu.com/questions/1289573/msmtp-sendmail-account-default-not-found-no-configuration-file-available-sys

- name: Install msmtp package
  apt:
    pkg:
    - msmtp

- name: Copia msmtprc.j2
  template:
    src: ./msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: msmtp
    mode: 0640

- name: Default mailrc
  copy:
    dest: "/etc/mailrc"
    content: |
      set sendmail="/usr/bin/msmtp"
    owner: root
    group: root