---
- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: restart bind9
  service:
    name: bind9
    state: restarted

- name: restart vsftpd
  service:
    name: vsftpd
    state: restarted
