---
#### Impressoras ipp

- name: Copy ppds to cups server
  template:
    src: "ppds/{{item}}"
    dest: "/usr/share/cups/model/{{item}}"
    mode: '0755'
  loop:
    - K7600.ppd
    - E82660.ppd

# read csv printers
- name: read printers from csv file
  set_fact:
    printersfile: "{{ lookup('file', tasks_cups_printers_csv) }}"

- name: csv to list
  set_fact:
    printers: "{{ printersfile.split('\n') }}"

# https://docs.oracle.com/cd/E19082-01/819-7761/gfjet/index.html
# -m everywhere OU
# -P /usr/share/cups/model/E82660.ppd
- name: Install printers com ppd
  shell: >
    /usr/sbin/lpadmin -p {{ item.split(',')[0] }}_ipp_ppd
    -m everywhere
    -o printer-error-policy=abort-job
    -o printer-is-shared=true
    -o PageSize=A4
    -o Media=A4
    -o sides=two-sided-long-edge
    -o Duplex=DuplexNoTumble
    -o InputSlot=Tray2
    - -E
  with_items:
    - "{{ printers }}"
