- name: install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: True
  vars:
     packages:
     - printer-driver-cups-pdf

# debian 9
#    -P /usr/share/ppd/cups-pdf/CUPS-PDF.ppd
# debian 11
#    -P /usr/share/ppd/cups-pdf/CUPS-PDF_opt.ppd

- name: Install pdfprinter
  shell: >
    /usr/sbin/lpadmin -p pdfprinter  
    -v tea4cups:cups-pdf:/
    -P /usr/share/ppd/cups-pdf/CUPS-PDF_opt.ppd
    -o printer-error-policy=abort-job
    -o printer-is-shared=true
    -o PageSize=A4
    -o Media=A4
    - -E
