---
#### Impressoras da próaluno

- name: Copy ppds to cups server
  template:
    src: "ppds/{{item}}"
    dest: "/usr/share/cups/model/{{item}}"
    mode: '0755'
  loop:
    - K7600.ppd
    - E82660.ppd

#    -m {{ item.model }}
- name: Install printers com ppd 
  shell: >
    /usr/sbin/lpadmin -p {{ item.name }}
    -v {{ item.device }}
    -m everywhere
    -o printer-error-policy=abort-job
    -o printer-is-shared=true
    -o PageSize=A4
    -o Media=A4
    - -E
  args:
    chdir: /usr/share/cups/model
  loop: "{{ proaluno_printers }}"
  vars:
    proaluno_printers:
      - name: "adm_hp_pb_e82660_fin_ipp_ppd"
        device: "ipp://10.80.0.7/ipp/printer"
        model: "/usr/share/cups/model/E82660.ppd"

      - name: "gh_hp_pb_e82660_proaluno_ipp_ppd_1"
        device: "ipp://10.80.0.32/ipp/printer"
        model: "/usr/share/cups/model/E82660.ppd"

      - name: "gh_hp_pb_e82660_proaluno_ipp_ppd_2"
        device: "ipp://10.80.0.51/ipp/printer"
        model: "/usr/share/cups/model/E82660.ppd"

      - name: "let_hp_pb_e82660_proaluno_ipp_ppd_1"
        device: "ipp://10.80.0.31/ipp/printer"
        model: "/usr/share/cups/model/E82660.ppd"
